CREATE DATABASE IF NOT EXISTS love_db;

USE love_db;

CREATE TABLE IF NOT EXISTS user_choices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    your_name VARCHAR(100) NOT NULL,
    crush_name VARCHAR(100) NOT NULL,
    vodka BOOLEAN DEFAULT FALSE,
    beer BOOLEAN DEFAULT FALSE,
    rum BOOLEAN DEFAULT FALSE,
    whiskey BOOLEAN DEFAULT FALSE,
    scotch BOOLEAN DEFAULT FALSE,
    wine BOOLEAN DEFAULT FALSE,
    desi BOOLEAN DEFAULT FALSE,
    cigarette BOOLEAN DEFAULT FALSE,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
